server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/anime?createDatabaseIfNotExist=true
    username: root
    password: nomad65107
  jpa:
      hibernate:
        ddl-auto: update
      show-sql: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: trace